apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ansible-mcp.fullname" . }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-log-svc"}]'
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-ansible-mcp"
    {{- include "ansible-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ansible-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ansible-mcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- if eq .Values.image.usePullSecret true }}
      imagePullSecrets:
      - name: {{ include "ansible-mcp.fullname" . }}-pull-secret
      {{- end }}
      {{ if eq .Values.useServiceAccount true }}
      serviceAccountName: {{ include "ansible-mcp.fullname" . }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.port }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /projects/static/home
            name: home-config
            readOnly: true
          - mountPath: /projects/static/learning-paths
            name: learning-paths-config
            readOnly: true
          - mountPath: /projects/static/tech-radar
            name: tech-radar-config
            readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.image.port }}
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - configMap:
          defaultMode: 511
          items:
          - key: data.json
            path: data.json
          name: {{ include "ansible-mcp.fullname" . }}-home
        name: home-config
      - configMap:
          defaultMode: 511
          items:
          - key: data.json
            path: data.json
          name: {{ include "ansible-mcp.fullname" . }}-learning-paths
        name: learning-paths-config
      - configMap:
          defaultMode: 511
          items:
          - key: data.json
            path: data.json
          name: {{ include "ansible-mcp.fullname" . }}-tech-radar
        name: tech-radar-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
