apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"app"}]'
  labels:
    app: svc
    app.kubernetes.io/component: svc
    app.kubernetes.io/instance: svc
    app.kubernetes.io/name: ansible-mcp
    app.kubernetes.io/part-of: ansible-mcp
  name: {{ include "ansible-mcp.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "ansible-mcp.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
